version: "3"
services:
  assignment-jdbc:
    image: assignmentproduct-jdbc
    ports:
      - "8081:8081"
    networks:
      - assignment-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:5.7
    networks:
      - assignment-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=manager
      - MYSQL_DATABASE=PA 
networks:
  assignment-mysql: